name: flutter_game
description: My First Flutter App

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

environment:
  sdk: '>=2.10.0 <3.0.0'